# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
# check on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.2

# owo-lib
# check on https://github.com/wisp-forest/owo-lib/releases/
owo_version=0.11.2+1.20

# mixinextras
# check on https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.0-beta.2

# Mod Properties
mod_version=1.2.0+1.20
maven_group=global.oskar
archives_base_name=gottagofast

